Redis user session
clickviewapp/GoodStuff pull request #6
Opened 2021-09-01 03:30 UTC by happymancoder

Merged after #5 

* Added implementation of persistent redis store for `IUserSessionStore`

2021-09-07 02:18 UTC, MrSmoke requested changes

2021-09-07 02:18 UTC, MrSmoke commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +﻿namespace ClickView.GoodStuff.AspNetCore.Authentication.StackExchangeRedis
would it be possible to move this into its own project? just so if we end up using something like MySql for session storage in a project we dont need to install all the redis packages?

2021-09-07 02:18 UTC, MrSmoke commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +            var options = cacheOptions.Value;
if your testing options for null below, might also be worth checking `cacheOptions` for null

2021-09-07 02:18 UTC, MrSmoke commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +            return session.HasValue ? JsonConvert.DeserializeObject<UserSession>(session.ToString()) : null;
could we use `System.Text.Json` instead? I don't think we need full blown newtonsoft, and it also be serialize to a byte array which works nicely with redis

2021-09-07 02:18 UTC, MrSmoke commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +            return _database.StringSetAsync(GetSessionIdKey(session.SessionId), session.Key, _expiry);
ah in #7 i added expire times to the session (forgot) so this should probably use that instead

2021-09-13 04:52 UTC, happymancoder commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +            return _database.StringSetAsync(GetSessionIdKey(session.SessionId), session.Key, _expiry);
done.

2021-09-13 04:53 UTC, happymancoder commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +            return session.HasValue ? JsonConvert.DeserializeObject<UserSession>(session.ToString()) : null;
done.

2021-09-13 04:53 UTC, happymancoder commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +            var options = cacheOptions.Value;
done.

2021-09-13 04:53 UTC, happymancoder commented on src/AspNetCore/Authentication/Authentication/src/StackExchangeRedis/RedisUserSessionStore.cs
> +﻿namespace ClickView.GoodStuff.AspNetCore.Authentication.StackExchangeRedis
done.

2021-09-13 04:54 UTC, MrSmoke approved these changes

2021-09-13 04:54 UTC, merged