Add ClickView.Goodstuff.Repositories.Snowflake
clickviewapp/GoodStuff pull request #75
Opened 2023-05-09 08:43 UTC by kevinwell

2023-09-17 23:30 UTC, MrSmoke commented on src/Repositories/Snowflake/src/BaseSnowflakeRepository.cs
> +        protected async Task<int> ExecuteAsync(string sql, object? param = null)
could you add cancellation token on these too?

2023-09-17 23:31 UTC, MrSmoke requested changes

2023-09-17 23:31 UTC, MrSmoke commented on src/Repositories/Snowflake/src/ClickView.GoodStuff.Repositories.Snowflake.csproj
> +        <PackageReference Include="Dapper" Version="2.0.123" />
Could you update Dapper? https://github.com/clickviewapp/GoodStuff/pull/95

2026-03-11 06:09 UTC, kevinwell commented on src/Repositories/Snowflake/src/ClickView.GoodStuff.Repositories.Snowflake.csproj
> +        <PackageReference Include="Dapper" Version="2.0.123" />
Done

2026-03-11 06:42 UTC, merged